[2022-06-09 16:05:22] [INFO] [Recovery] 2022/06/09 - 16:05:22 panic recovered:
record not found
C:/Users/mensyli1/work/workspace/mwpath/pkg/mod/github.com/toolkits/pkg@v1.2.9/errorx/errorx.go:40 (0x1aeb9fa)
	Dangerous: }
C:/Users/mensyli1/work/workspace/mwpath/pkg/mod/github.com/toolkits/pkg@v1.2.9/ginx/errorx.go:10 (0x1b1fa09)
	Dangerous: }
C:/Users/mensyli1/work/workspace/middleware/src/controller/postgres/postgres.go:42 (0x1b1f9f8)
	GetById: }
C:/Users/mensyli1/work/workspace/mwpath/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x1b23127)
	(*Context).Next: c.index++
C:/Users/mensyli1/work/workspace/middleware/src/util/aop/jwt.go:19 (0x1b2310e)
	Auth.func1: 
C:/Users/mensyli1/work/workspace/mwpath/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x1b2324b)
	(*Context).Next: c.index++
C:/Users/mensyli1/work/workspace/middleware/src/util/aop/logrus.go:62 (0x1b23228)
	Logrus.func1: //ÁªìÊùüÊó∂Èó¥
C:/Users/mensyli1/work/workspace/mwpath/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x1b221ba)
	(*Context).Next: c.index++
C:/Users/mensyli1/work/workspace/middleware/src/util/aop/recovery.go:94 (0x1b221a6)
	CustomRecoveryWithWriter.func1: }
C:/Users/mensyli1/work/workspace/mwpath/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x1ac529d)
	(*Context).Next: c.index++
C:/Users/mensyli1/work/workspace/mwpath/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489 (0x1ac4f25)
	(*Engine).handleHTTPRequest: c.writermem.WriteHeaderNow()
C:/Users/mensyli1/work/workspace/mwpath/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445 (0x1ac4a84)
	(*Engine).ServeHTTP: 
C:/install/Dev/Env/Go/src/net/http/server.go:2879 (0xe2459a)
	serverHandler.ServeHTTP: }
C:/install/Dev/Env/Go/src/net/http/server.go:1930 (0xe1fc47)
	(*conn).serve: w.cancelCtx()
C:/install/Dev/Env/Go/src/runtime/asm_amd64.s:1581 (0xb74b00)
	goexit: CALL	runtime¬∑goexit1(SB)	// does not return
[0m (github.com/mensylisir/kmpp-middleware/src/util/aop.CustomRecoveryWithWriter.func1.1: 82) {map[]} 
