[2022-06-15 09:16:04] [ERROR] gather cluster info error: Get "https://192.168.111.100:6443/version?timeout=32s": dial tcp 192.168.111.100:6443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (github.com/mensylisir/kmpp-middleware/src/cron/job.(*WatchClusterInfo).Run.func1: 34) {map[]} 
[2022-06-15 09:16:42] [INFO]  (github.com/mensylisir/kmpp-middleware/src/util/aop.Logrus.func1: 83) {map[client_ip:172.30.1.74 latency_time:0s req_method:GET req_uri:/api/v1/pod/logs?cluster_id=4e4036eb-5acb-44ea-9aa9-6bf24a5b9671&namespace=default&pod_name=postgres-operator-5847d7cd7-4x5pp status_code:404]} 
[2022-06-15 09:16:44] [INFO]  (github.com/mensylisir/kmpp-middleware/src/util/aop.Logrus.func1: 83) {map[client_ip:172.30.1.74 latency_time:0s req_method:GET req_uri:/api/v1/pod/logs?cluster_id=4e4036eb-5acb-44ea-9aa9-6bf24a5b9671&namespace=default&pod_name=postgres-operator-5847d7cd7-4x5pp status_code:404]} 
[2022-06-15 09:16:54] [INFO]  (github.com/mensylisir/kmpp-middleware/src/util/aop.Logrus.func1: 83) {map[client_ip:172.30.1.74 latency_time:19.0019ms req_method:GET req_uri:/api/v1/postgressqls?page=1&size=50&user_id=5e81095f-3c0c-4cb2-8033-bde03d601357 status_code:200]} 
